memoreco/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'memos#index'
  get 'top/login'
  post 'top/login'
  get 'top/logout'
  get 'memos/index'
  get 'memos/new'
  resources :memos
  resources :likes
  resources :users
end

memoreco/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

memoreco/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :memo
  belongs_to :user
end

memoreco/app/models/memo.rb
class Memo < ApplicationRecord
  validates :memo, presence: true, length: {maximum: 140}
  
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, source: :user, through: :likes
  
  def like(user)
    likes.create(user_id: user.id)
  end
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  def liked?(user)
    like_users.include?(user)
  end
end

memoreco/app/models/user.rb
class User < ApplicationRecord
    def self.authenticate(uid, pass)
        user = User.find_by(uid: uid)
        if user and BCrypt::Password.new(user.pass) == pass
            user
        else
            nil
        end
    end
  
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

memoreco/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_user
            if session[:login_uid]
                User.find_by(uid: session[:login_uid])
            end
        end
        def create
            @post = Post.new(
            content: params[:content],
            user_id: @current_user.id)
        end
        helper_method :current_user
end

memoreco/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    memo = Memo.find(params[:memo_id])
    unless memo.liked?(current_user)
      memo.like(current_user)
    end
    redirect_to root_path
  end

  def destroy
    memo = Memo.find(params[:id])
    if memo.liked?(current_user)
      memo.unlike(current_user)
    end
    redirect_to root_path
  end
end

memoreco/app/controllers/memos_controller.rb
class MemosController < ApplicationController
    def index
        if current_user
            @memos = Memo.all
        else
            redirect_to top_login_path
        end
    end
    def new
        @memo = Memo.new
    end
    def show
        @memo = Memo.find(params[:id])
    end
    def edit
        @memo = Memo.find(params[:id])
    end
    def update
        @memo = Memo.find(params[:id])
        if @memo.update(
            title: params[:memo][:title],
            directer: params[:memo][:directer],
            release: params[:memo][:release],
            memo: params[:memo][:memo])
            redirect_to root_path
        else
            render :edit
        end
    end
    def create
        @memo = Memo.new(
            user_id: User.find_by(uid: session[:login_uid]).id,
            title: params[:memo][:title],
            directer: params[:memo][:directer],
            release: params[:memo][:release],
            memo: params[:memo][:memo])
        if @memo.save
            redirect_to root_path
        else
            render new_memo_path
        end
    end
    def destroy
        memo = Memo.find(params[:id])
        memo.destroy
        redirect_to '/'
    end
end

memoreco/app/controllers/top_controller.rb
class TopController < ApplicationController
    def login
    user = User.authenticate(params[:uid],params[:pass])
        if user
            session[:login_uid] = params[:uid]
            redirect_to root_path
        else
            render top_login_path
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end
class TopController < ApplicationController
    def login
    user = User.authenticate(params[:uid],params[:pass])
        if user
            session[:login_uid] = params[:uid]
            redirect_to root_path
        else
            render top_login_path
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end

memoreco/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        pass = BCrypt::Password.create(params[:user][:pass])
        @user = User.new(uid: params[:user][:uid], pass: pass)
        if @user.save
            flash[:info] = '登録完了'
            redirect_to users_path
        else
            render new_user_path
        end
    end
    
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to users_path
    end
end

memoreco/app/helpers/application_helper.rb
module ApplicationHelper
end

memoreco/app/helpers/likes_helper.rb
module LikesHelper
end

memoreco/app/helpers/memo_helper.rb
module MemoHelper
end

memoreco/app/helpers/top_helper.rb
module TopHelper
end

memoreco/app/helpers/users_helper.rb
module UsersHelper
end

memoreco/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memoreco</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

memoreco/app/views/memos/edit.html.erb
<h1>編集ページ</h1>

<%= form_for @memo, url: {action: :update} do |form| %>
  <p>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :directer, "監督" %>
    <%= form.text_field :directer %>
    <br>
    <%= form.label :release, "公開日" %>
    <%= form.text_field :release %>
    <br>
    <%= form.label :memo, "レビュー" %>
    <%= form.text_area :memo %>
    <br>
    <br>
    <input type="submit" value="更新する" class="button">
  </p>
<% end %>

<p><%= link_to '戻る', root_path %></p>

memoreco/app/views/memos/index.html.erb
<h1>メモレコ</h1>

<% user = User.find_by(uid: session[:login_uid]) %>
<% @memos.each do |m| %>
<p>
    <% User.find(m.user_id).uid %>
    <%= link_to m.title, "/memos/#{m.id}"%>
    <% if current_user and m.user_id == current_user.id %>
     <%= link_to '編集', "/memos/#{m.id}/edit" %>
     <%= link_to '削除', "/memos/#{m.id}",method: :delete %>
    <% end %>
    <% if current_user %>
     <% if Like.find_by(user_id: user.id, memo_id: m.id) %>
       <%= link_to '♥️', like_path(m), method: :delete %>
     <% else %>
       <%= link_to '♡', likes_path(memo_id: m.id), method: :post %>
     <% end %>
    <% end %>
</p>
<% end %>






<% if session[:login_uid] %>
    <p>login中</p>
    <p><%= session[:login_uid] %></p>
<% end %>


<div class = "simple_square_btn">
<%= link_to '新規追加','/memos/new' %>
<%= link_to 'ログアウト', top_logout_path %>
</div>

memoreco/app/views/memos/new.html.erb
<h1>投稿ページ</h1>

<%= form_for @memo, url: {action: :create} do |form| %>
  <p>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :directer, "監督" %>
    <%= form.text_field :directer %>
    <br>
    <%= form.label :release, "公開日" %>
    <%= form.text_field :release %>
    <br>
    <%= form.label :memo, "レビュー" %>
    <%= form.text_area :memo %>
    <br>
    <br>
    <input type="submit" value="投稿する" class="button">
  </p>
<% end %>


<p><%= link_to '戻る', root_path %></p>

memoreco/app/views/memos/show.html.erb
<h1>詳細ページ</h1>

<p>
    <strong>タイトル：</strong>
    <%= @memo.title %>
</p>
<p>
    <strong>監督：</strong>
    <%= @memo.directer %>
</p>
<p>
    <strong>公開日：</strong>
    <%= @memo.release %>
</p>
<p>
    <strong>レビュー：</strong>
    <%= @memo.memo %>
</p>

<%= link_to '戻る','/' %>

memoreco/app/views/top/login.html.erb
<h1>メモレコ</h1>

<% if flash[:info] %>
    <%= flash[:info] %>
<% end %>

<%= form_tag top_login_path, method: :post do %>
  <center>
    <div class = "a">
    <%= label_tag :uid, 'ユーザID' %>
    <%= text_field_tag :uid %>
    <br>
    <br>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <br>
    <br>
　　<input type="submit" value="ログイン" class="button">
　　</div>
<% end %>

<p>
  初めての方はこちら
  <%= link_to '新規登録', new_user_path %>
  </center>
</p>
  

memoreco/app/views/users/index.html.erb
<h1>ユーザ一覧</h1>

<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<% @users.each do |e| %>
<p>
    <%= e.uid %>
    <%= e.pass %>
    <%= link_to '削除', user_path(e), method: :delete %>
</p>
<% end %>

<p><%= link_to '新規登録', new_user_path %></p>

<p><%= link_to '戻る', :back %></p>

<% if current_user %>
  <p><%= link_to 'ログアウト', top_logout_path %></p>
<% else %>
  <p><%= link_to 'ログイン', top_login_path %></p>
<% end %>

<% if session[:login_uid] %>
    <p>login中</p>
    <p><%= session[:login_uid] %></p>
<% end %>

memoreco/app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_for @user, url: {action: :create} do |f| %>
<center>
  <div class = "a">
    <%= f.label :uid, 'ユーザID' %>
    <%= f.text_field :uid %>
    <br>
    <br>
    <%= f.label :uid, 'パスワード' %>
    <%= f.password_field :pass %>
    <br>
    <br>
    <%= f.label :uid, 'パスワード確認用' %>
    <%= f.password_field :pass %>
    <br>
    <br>
　  <input type="submit" value="登録する" class="button">
　</div>
</p>
<% end %>

<p><%= link_to '戻る', top_login_path %></p>
</center>